
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DbEntity`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=YongDb;Persist Security Info=True;User ID=sa;password=**zapped**;MultipleActiveResultSets=True`
//     Schema:                 ``
//     Include Views:          `True`

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace DbEntity
{
	public partial class DbEntityDB : Database
	{
		public DbEntityDB() 
			: base("DbEntity")
		{
			CommonConstruct();
		}

		public DbEntityDB(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
			DbEntityDB GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static DbEntityDB GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			else
				return new DbEntityDB();
        }

		[ThreadStatic] static DbEntityDB _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        
		[Serializable]
		public partial class Record<T> where T:class,new()
		{
			//public T Copy()
			//{
				//return DoubleBullet.Surmnt.FrameWork.Entity.FrameWorkBaseEntity.DeSerialize<T>(DoubleBullet.Surmnt.FrameWork.Entity.FrameWorkBaseEntity.Serialize<T>(this as T));
				//return Ultra.Web.Core.Common.ObjectHelper.DeepCopy<T>(this as T);
			//}
			public static DbEntityDB repo { get { return DbEntityDB.GetInstance(); } }
			public bool IsNew() { return repo.IsNew(this); }
			public object Insert() { return repo.Insert(this); }
			public int Update(IEnumerable<string> columns) { return repo.Update(this, columns); }
			public static int Update(string sql, params object[] args) { return repo.Update<T>(sql, args); }
			public static int Update(Sql sql) { return repo.Update<T>(sql); }
			public int Delete() { return repo.Delete(this); }
			public static int Delete(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Delete(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(object primaryKey) { return repo.Delete<T>(primaryKey); }
			public static bool Exists(object primaryKey) { return repo.Exists<T>(primaryKey); }
			public static T SingleOrDefault(object primaryKey) { return repo.SingleOrDefault<T>(primaryKey); }
			public static T SingleOrDefault(string sql, params object[] args) { return repo.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Sql sql) { return repo.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(string sql, params object[] args) { return repo.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Sql sql) { return repo.FirstOrDefault<T>(sql); }
			public static T Single(object primaryKey) { return repo.Single<T>(primaryKey); }
			public static T Single(string sql, params object[] args) { return repo.Single<T>(sql, args); }
			public static T Single(Sql sql) { return repo.Single<T>(sql); }
			public static T First(string sql, params object[] args) { return repo.First<T>(sql, args); }
			public static T First(Sql sql) { return repo.First<T>(sql); }
			public static List<T> Fetch(string sql, params object[] args) { return repo.Fetch<T>(sql, args); }
			public static List<T> Fetch(Sql sql) { return repo.Fetch<T>(sql); }
			public static List<T> Fetch(long page, long itemsPerPage, string sql, params object[] args) { return repo.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(long page, long itemsPerPage, Sql sql) { return repo.Fetch<T>(page, itemsPerPage, sql); }
			public static List<T> SkipTake(long skip, long take, string sql, params object[] args) { return repo.SkipTake<T>(skip, take, sql, args); }
			public static List<T> SkipTake(long skip, long take, Sql sql) { return repo.SkipTake<T>(skip, take, sql); }
			public static Page<T> Page(long page, long itemsPerPage, string sql, params object[] args) { return repo.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(long page, long itemsPerPage, Sql sql) { return repo.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(string sql, params object[] args) { return repo.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Sql sql) { return repo.Query<T>(sql); }
			
			private Dictionary<string,bool> ModifiedColumns;
			private void OnLoaded()
			{
				ModifiedColumns = new Dictionary<string,bool>();
			}
			protected void MarkColumnModified(string column_name)
			{
				if (ModifiedColumns!=null)
					ModifiedColumns[column_name]=true;
			}
			public int Update() 
			{ 
				if (ModifiedColumns==null)
					return repo.Update(this); 

				int retv = repo.Update(this, ModifiedColumns.Keys);
				ModifiedColumns.Clear();
				return retv;
			}
			public void Save() 
			{ 
				if (repo.IsNew(this))
					repo.Insert(this);
				else
					Update();
			}
		}
	}
	

    
	[TableName("t_adjinvt")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_adjinvt : DbEntityDB.Record<t_adjinvt>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("AdjInvtNo")]
        [Column] 
		public string AdjInvtNo 
		{ 
			get
			{
				return _AdjInvtNo;
			}
			set
			{
				_AdjInvtNo = value;
				MarkColumnModified("AdjInvtNo");
			}
		}
		string _AdjInvtNo;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("Num")]
        [Column] 
		public int Num 
		{ 
			get
			{
				return _Num;
			}
			set
			{
				_Num = value;
				MarkColumnModified("Num");
			}
		}
		int _Num;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("IsAudit")]
        [Column] 
		public bool IsAudit 
		{ 
			get
			{
				return _IsAudit;
			}
			set
			{
				_IsAudit = value;
				MarkColumnModified("IsAudit");
			}
		}
		bool _IsAudit;


        [System.Xml.Serialization.XmlElement("AuditDate")]
        [Column] 
		public DateTime AuditDate 
		{ 
			get
			{
				return _AuditDate;
			}
			set
			{
				_AuditDate = value;
				MarkColumnModified("AuditDate");
			}
		}
		DateTime _AuditDate;


        [System.Xml.Serialization.XmlElement("IsInvalid")]
        [Column] 
		public bool IsInvalid 
		{ 
			get
			{
				return _IsInvalid;
			}
			set
			{
				_IsInvalid = value;
				MarkColumnModified("IsInvalid");
			}
		}
		bool _IsInvalid;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_forcedoffline")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_forcedoffline : DbEntityDB.Record<t_forcedoffline>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("LoginMAC")]
        [Column] 
		public string LoginMAC 
		{ 
			get
			{
				return _LoginMAC;
			}
			set
			{
				_LoginMAC = value;
				MarkColumnModified("LoginMAC");
			}
		}
		string _LoginMAC;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_instock")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_instock : DbEntityDB.Record<t_instock>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("InStockNo")]
        [Column] 
		public string InStockNo 
		{ 
			get
			{
				return _InStockNo;
			}
			set
			{
				_InStockNo = value;
				MarkColumnModified("InStockNo");
			}
		}
		string _InStockNo;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("Num")]
        [Column] 
		public int Num 
		{ 
			get
			{
				return _Num;
			}
			set
			{
				_Num = value;
				MarkColumnModified("Num");
			}
		}
		int _Num;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("IsAudit")]
        [Column] 
		public bool IsAudit 
		{ 
			get
			{
				return _IsAudit;
			}
			set
			{
				_IsAudit = value;
				MarkColumnModified("IsAudit");
			}
		}
		bool _IsAudit;


        [System.Xml.Serialization.XmlElement("AuditDate")]
        [Column] 
		public DateTime AuditDate 
		{ 
			get
			{
				return _AuditDate;
			}
			set
			{
				_AuditDate = value;
				MarkColumnModified("AuditDate");
			}
		}
		DateTime _AuditDate;


        [System.Xml.Serialization.XmlElement("IsInvalid")]
        [Column] 
		public bool IsInvalid 
		{ 
			get
			{
				return _IsInvalid;
			}
			set
			{
				_IsInvalid = value;
				MarkColumnModified("IsInvalid");
			}
		}
		bool _IsInvalid;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;


        [System.Xml.Serialization.XmlElement("OuterNo")]
        [Column] 
		public string OuterNo 
		{ 
			get
			{
				return _OuterNo;
			}
			set
			{
				_OuterNo = value;
				MarkColumnModified("OuterNo");
			}
		}
		string _OuterNo;

	}
    
	[TableName("t_logincur")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_logincur : DbEntityDB.Record<t_logincur>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("UserName")]
        [Column] 
		public string UserName 
		{ 
			get
			{
				return _UserName;
			}
			set
			{
				_UserName = value;
				MarkColumnModified("UserName");
			}
		}
		string _UserName;


        [System.Xml.Serialization.XmlElement("LoginMAC")]
        [Column] 
		public string LoginMAC 
		{ 
			get
			{
				return _LoginMAC;
			}
			set
			{
				_LoginMAC = value;
				MarkColumnModified("LoginMAC");
			}
		}
		string _LoginMAC;


        [System.Xml.Serialization.XmlElement("ExternalIP")]
        [Column] 
		public string ExternalIP 
		{ 
			get
			{
				return _ExternalIP;
			}
			set
			{
				_ExternalIP = value;
				MarkColumnModified("ExternalIP");
			}
		}
		string _ExternalIP;


        [System.Xml.Serialization.XmlElement("LocalIP")]
        [Column] 
		public string LocalIP 
		{ 
			get
			{
				return _LocalIP;
			}
			set
			{
				_LocalIP = value;
				MarkColumnModified("LocalIP");
			}
		}
		string _LocalIP;


        [System.Xml.Serialization.XmlElement("LoginTime")]
        [Column] 
		public DateTime LoginTime 
		{ 
			get
			{
				return _LoginTime;
			}
			set
			{
				_LoginTime = value;
				MarkColumnModified("LoginTime");
			}
		}
		DateTime _LoginTime;


        [System.Xml.Serialization.XmlElement("LastUpdateTime")]
        [Column] 
		public DateTime LastUpdateTime 
		{ 
			get
			{
				return _LastUpdateTime;
			}
			set
			{
				_LastUpdateTime = value;
				MarkColumnModified("LastUpdateTime");
			}
		}
		DateTime _LastUpdateTime;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_loginfail")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_loginfail : DbEntityDB.Record<t_loginfail>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("UserName")]
        [Column] 
		public string UserName 
		{ 
			get
			{
				return _UserName;
			}
			set
			{
				_UserName = value;
				MarkColumnModified("UserName");
			}
		}
		string _UserName;


        [System.Xml.Serialization.XmlElement("LoginMAC")]
        [Column] 
		public string LoginMAC 
		{ 
			get
			{
				return _LoginMAC;
			}
			set
			{
				_LoginMAC = value;
				MarkColumnModified("LoginMAC");
			}
		}
		string _LoginMAC;


        [System.Xml.Serialization.XmlElement("ExternalIP")]
        [Column] 
		public string ExternalIP 
		{ 
			get
			{
				return _ExternalIP;
			}
			set
			{
				_ExternalIP = value;
				MarkColumnModified("ExternalIP");
			}
		}
		string _ExternalIP;


        [System.Xml.Serialization.XmlElement("LocalIP")]
        [Column] 
		public string LocalIP 
		{ 
			get
			{
				return _LocalIP;
			}
			set
			{
				_LocalIP = value;
				MarkColumnModified("LocalIP");
			}
		}
		string _LocalIP;


        [System.Xml.Serialization.XmlElement("LoginTime")]
        [Column] 
		public DateTime LoginTime 
		{ 
			get
			{
				return _LoginTime;
			}
			set
			{
				_LoginTime = value;
				MarkColumnModified("LoginTime");
			}
		}
		DateTime _LoginTime;


        [System.Xml.Serialization.XmlElement("LastUpdateTime")]
        [Column] 
		public DateTime LastUpdateTime 
		{ 
			get
			{
				return _LastUpdateTime;
			}
			set
			{
				_LastUpdateTime = value;
				MarkColumnModified("LastUpdateTime");
			}
		}
		DateTime _LastUpdateTime;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_mac")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_mac : DbEntityDB.Record<t_mac>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("Mac")]
        [Column] 
		public string Mac 
		{ 
			get
			{
				return _Mac;
			}
			set
			{
				_Mac = value;
				MarkColumnModified("Mac");
			}
		}
		string _Mac;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_member")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_member : DbEntityDB.Record<t_member>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("ReceiverName")]
        [Column] 
		public string ReceiverName 
		{ 
			get
			{
				return _ReceiverName;
			}
			set
			{
				_ReceiverName = value;
				MarkColumnModified("ReceiverName");
			}
		}
		string _ReceiverName;


        [System.Xml.Serialization.XmlElement("ReceiverNo")]
        [Column] 
		public string ReceiverNo 
		{ 
			get
			{
				return _ReceiverNo;
			}
			set
			{
				_ReceiverNo = value;
				MarkColumnModified("ReceiverNo");
			}
		}
		string _ReceiverNo;


        [System.Xml.Serialization.XmlElement("ReceiverMobile")]
        [Column] 
		public string ReceiverMobile 
		{ 
			get
			{
				return _ReceiverMobile;
			}
			set
			{
				_ReceiverMobile = value;
				MarkColumnModified("ReceiverMobile");
			}
		}
		string _ReceiverMobile;


        [System.Xml.Serialization.XmlElement("ReceiverAddress")]
        [Column] 
		public string ReceiverAddress 
		{ 
			get
			{
				return _ReceiverAddress;
			}
			set
			{
				_ReceiverAddress = value;
				MarkColumnModified("ReceiverAddress");
			}
		}
		string _ReceiverAddress;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_menu")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_menu : DbEntityDB.Record<t_menu>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("Version")]
        [Column] 
		public string Version 
		{ 
			get
			{
				return _Version;
			}
			set
			{
				_Version = value;
				MarkColumnModified("Version");
			}
		}
		string _Version;


        [System.Xml.Serialization.XmlElement("MenuXml")]
        [Column] 
		public string MenuXml 
		{ 
			get
			{
				return _MenuXml;
			}
			set
			{
				_MenuXml = value;
				MarkColumnModified("MenuXml");
			}
		}
		string _MenuXml;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_order")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_order : DbEntityDB.Record<t_order>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("TradeGuid")]
        [Column] 
		public Guid TradeGuid 
		{ 
			get
			{
				return _TradeGuid;
			}
			set
			{
				_TradeGuid = value;
				MarkColumnModified("TradeGuid");
			}
		}
		Guid _TradeGuid;


        [System.Xml.Serialization.XmlElement("ItemGuid")]
        [Column] 
		public Guid ItemGuid 
		{ 
			get
			{
				return _ItemGuid;
			}
			set
			{
				_ItemGuid = value;
				MarkColumnModified("ItemGuid");
			}
		}
		Guid _ItemGuid;


        [System.Xml.Serialization.XmlElement("ItemName")]
        [Column] 
		public string ItemName 
		{ 
			get
			{
				return _ItemName;
			}
			set
			{
				_ItemName = value;
				MarkColumnModified("ItemName");
			}
		}
		string _ItemName;


        [System.Xml.Serialization.XmlElement("ItemNo")]
        [Column] 
		public string ItemNo 
		{ 
			get
			{
				return _ItemNo;
			}
			set
			{
				_ItemNo = value;
				MarkColumnModified("ItemNo");
			}
		}
		string _ItemNo;


        [System.Xml.Serialization.XmlElement("Price")]
        [Column] 
		public decimal Price 
		{ 
			get
			{
				return _Price;
			}
			set
			{
				_Price = value;
				MarkColumnModified("Price");
			}
		}
		decimal _Price;


        [System.Xml.Serialization.XmlElement("PointFee")]
        [Column] 
		public decimal PointFee 
		{ 
			get
			{
				return _PointFee;
			}
			set
			{
				_PointFee = value;
				MarkColumnModified("PointFee");
			}
		}
		decimal _PointFee;


        [System.Xml.Serialization.XmlElement("OrderPrice")]
        [Column] 
		public decimal OrderPrice 
		{ 
			get
			{
				return _OrderPrice;
			}
			set
			{
				_OrderPrice = value;
				MarkColumnModified("OrderPrice");
			}
		}
		decimal _OrderPrice;


        [System.Xml.Serialization.XmlElement("Num")]
        [Column] 
		public int Num 
		{ 
			get
			{
				return _Num;
			}
			set
			{
				_Num = value;
				MarkColumnModified("Num");
			}
		}
		int _Num;


        [System.Xml.Serialization.XmlElement("OrderPointFee")]
        [Column] 
		public decimal OrderPointFee 
		{ 
			get
			{
				return _OrderPointFee;
			}
			set
			{
				_OrderPointFee = value;
				MarkColumnModified("OrderPointFee");
			}
		}
		decimal _OrderPointFee;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_role")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_role : DbEntityDB.Record<t_role>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("Name")]
        [Column] 
		public string Name 
		{ 
			get
			{
				return _Name;
			}
			set
			{
				_Name = value;
				MarkColumnModified("Name");
			}
		}
		string _Name;


        [System.Xml.Serialization.XmlElement("Desc")]
        [Column] 
		public string Desc 
		{ 
			get
			{
				return _Desc;
			}
			set
			{
				_Desc = value;
				MarkColumnModified("Desc");
			}
		}
		string _Desc;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_roleset")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_roleset : DbEntityDB.Record<t_roleset>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("RoleName")]
        [Column] 
		public string RoleName 
		{ 
			get
			{
				return _RoleName;
			}
			set
			{
				_RoleName = value;
				MarkColumnModified("RoleName");
			}
		}
		string _RoleName;


        [System.Xml.Serialization.XmlElement("RoleId")]
        [Column] 
		public int RoleId 
		{ 
			get
			{
				return _RoleId;
			}
			set
			{
				_RoleId = value;
				MarkColumnModified("RoleId");
			}
		}
		int _RoleId;


        [System.Xml.Serialization.XmlElement("RoleSetTree")]
        [Column] 
		public string RoleSetTree 
		{ 
			get
			{
				return _RoleSetTree;
			}
			set
			{
				_RoleSetTree = value;
				MarkColumnModified("RoleSetTree");
			}
		}
		string _RoleSetTree;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_roleuser")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_roleuser : DbEntityDB.Record<t_roleuser>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("UserId")]
        [Column] 
		public int UserId 
		{ 
			get
			{
				return _UserId;
			}
			set
			{
				_UserId = value;
				MarkColumnModified("UserId");
			}
		}
		int _UserId;


        [System.Xml.Serialization.XmlElement("RoleId")]
        [Column] 
		public int RoleId 
		{ 
			get
			{
				return _RoleId;
			}
			set
			{
				_RoleId = value;
				MarkColumnModified("RoleId");
			}
		}
		int _RoleId;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_serialno")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_serialno : DbEntityDB.Record<t_serialno>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public long Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		long _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;


        [System.Xml.Serialization.XmlElement("Prefix")]
        [Column] 
		public string Prefix 
		{ 
			get
			{
				return _Prefix;
			}
			set
			{
				_Prefix = value;
				MarkColumnModified("Prefix");
			}
		}
		string _Prefix;


        [System.Xml.Serialization.XmlElement("Ending")]
        [Column] 
		public string Ending 
		{ 
			get
			{
				return _Ending;
			}
			set
			{
				_Ending = value;
				MarkColumnModified("Ending");
			}
		}
		string _Ending;


        [System.Xml.Serialization.XmlElement("LoopNum")]
        [Column] 
		public long LoopNum 
		{ 
			get
			{
				return _LoopNum;
			}
			set
			{
				_LoopNum = value;
				MarkColumnModified("LoopNum");
			}
		}
		long _LoopNum;


        [System.Xml.Serialization.XmlElement("Dep")]
        [Column] 
		public string Dep 
		{ 
			get
			{
				return _Dep;
			}
			set
			{
				_Dep = value;
				MarkColumnModified("Dep");
			}
		}
		string _Dep;

	}
    
	[TableName("t_trade")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_trade : DbEntityDB.Record<t_trade>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("ReceiverName")]
        [Column] 
		public string ReceiverName 
		{ 
			get
			{
				return _ReceiverName;
			}
			set
			{
				_ReceiverName = value;
				MarkColumnModified("ReceiverName");
			}
		}
		string _ReceiverName;


        [System.Xml.Serialization.XmlElement("ReceiverMobile")]
        [Column] 
		public string ReceiverMobile 
		{ 
			get
			{
				return _ReceiverMobile;
			}
			set
			{
				_ReceiverMobile = value;
				MarkColumnModified("ReceiverMobile");
			}
		}
		string _ReceiverMobile;


        [System.Xml.Serialization.XmlElement("ReceiverAddress")]
        [Column] 
		public string ReceiverAddress 
		{ 
			get
			{
				return _ReceiverAddress;
			}
			set
			{
				_ReceiverAddress = value;
				MarkColumnModified("ReceiverAddress");
			}
		}
		string _ReceiverAddress;


        [System.Xml.Serialization.XmlElement("MemberGuid")]
        [Column] 
		public Guid? MemberGuid 
		{ 
			get
			{
				return _MemberGuid;
			}
			set
			{
				_MemberGuid = value;
				MarkColumnModified("MemberGuid");
			}
		}
		Guid? _MemberGuid;


        [System.Xml.Serialization.XmlElement("Delivery")]
        [Column] 
		public string Delivery 
		{ 
			get
			{
				return _Delivery;
			}
			set
			{
				_Delivery = value;
				MarkColumnModified("Delivery");
			}
		}
		string _Delivery;


        [System.Xml.Serialization.XmlElement("DeliveryDate")]
        [Column] 
		public DateTime? DeliveryDate 
		{ 
			get
			{
				return _DeliveryDate;
			}
			set
			{
				_DeliveryDate = value;
				MarkColumnModified("DeliveryDate");
			}
		}
		DateTime? _DeliveryDate;


        [System.Xml.Serialization.XmlElement("Reminder")]
        [Column] 
		public string Reminder 
		{ 
			get
			{
				return _Reminder;
			}
			set
			{
				_Reminder = value;
				MarkColumnModified("Reminder");
			}
		}
		string _Reminder;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsSubmit")]
        [Column] 
		public bool? IsSubmit 
		{ 
			get
			{
				return _IsSubmit;
			}
			set
			{
				_IsSubmit = value;
				MarkColumnModified("IsSubmit");
			}
		}
		bool? _IsSubmit;


        [System.Xml.Serialization.XmlElement("IsPrint")]
        [Column] 
		public bool? IsPrint 
		{ 
			get
			{
				return _IsPrint;
			}
			set
			{
				_IsPrint = value;
				MarkColumnModified("IsPrint");
			}
		}
		bool? _IsPrint;


        [System.Xml.Serialization.XmlElement("PrintCnt")]
        [Column] 
		public int? PrintCnt 
		{ 
			get
			{
				return _PrintCnt;
			}
			set
			{
				_PrintCnt = value;
				MarkColumnModified("PrintCnt");
			}
		}
		int? _PrintCnt;


        [System.Xml.Serialization.XmlElement("Printor")]
        [Column] 
		public string Printor 
		{ 
			get
			{
				return _Printor;
			}
			set
			{
				_Printor = value;
				MarkColumnModified("Printor");
			}
		}
		string _Printor;


        [System.Xml.Serialization.XmlElement("PrintTime")]
        [Column] 
		public DateTime? PrintTime 
		{ 
			get
			{
				return _PrintTime;
			}
			set
			{
				_PrintTime = value;
				MarkColumnModified("PrintTime");
			}
		}
		DateTime? _PrintTime;


        [System.Xml.Serialization.XmlElement("IsInvalid")]
        [Column] 
		public bool? IsInvalid 
		{ 
			get
			{
				return _IsInvalid;
			}
			set
			{
				_IsInvalid = value;
				MarkColumnModified("IsInvalid");
			}
		}
		bool? _IsInvalid;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;


        [System.Xml.Serialization.XmlElement("Periods")]
        [Column] 
		public string Periods 
		{ 
			get
			{
				return _Periods;
			}
			set
			{
				_Periods = value;
				MarkColumnModified("Periods");
			}
		}
		string _Periods;

	}
    
	[TableName("t_inventory")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_inventory : DbEntityDB.Record<t_inventory>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("ItemName")]
        [Column] 
		public string ItemName 
		{ 
			get
			{
				return _ItemName;
			}
			set
			{
				_ItemName = value;
				MarkColumnModified("ItemName");
			}
		}
		string _ItemName;


        [System.Xml.Serialization.XmlElement("ItemNo")]
        [Column] 
		public string ItemNo 
		{ 
			get
			{
				return _ItemNo;
			}
			set
			{
				_ItemNo = value;
				MarkColumnModified("ItemNo");
			}
		}
		string _ItemNo;


        [System.Xml.Serialization.XmlElement("CostPrice")]
        [Column] 
		public decimal CostPrice 
		{ 
			get
			{
				return _CostPrice;
			}
			set
			{
				_CostPrice = value;
				MarkColumnModified("CostPrice");
			}
		}
		decimal _CostPrice;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("Qty")]
        [Column] 
		public int Qty 
		{ 
			get
			{
				return _Qty;
			}
			set
			{
				_Qty = value;
				MarkColumnModified("Qty");
			}
		}
		int _Qty;


        [System.Xml.Serialization.XmlElement("WareName")]
        [Column] 
		public string WareName 
		{ 
			get
			{
				return _WareName;
			}
			set
			{
				_WareName = value;
				MarkColumnModified("WareName");
			}
		}
		string _WareName;


        [System.Xml.Serialization.XmlElement("AreaName")]
        [Column] 
		public string AreaName 
		{ 
			get
			{
				return _AreaName;
			}
			set
			{
				_AreaName = value;
				MarkColumnModified("AreaName");
			}
		}
		string _AreaName;


        [System.Xml.Serialization.XmlElement("LocName")]
        [Column] 
		public string LocName 
		{ 
			get
			{
				return _LocName;
			}
			set
			{
				_LocName = value;
				MarkColumnModified("LocName");
			}
		}
		string _LocName;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_user")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_user : DbEntityDB.Record<t_user>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("UserName")]
        [Column] 
		public string UserName 
		{ 
			get
			{
				return _UserName;
			}
			set
			{
				_UserName = value;
				MarkColumnModified("UserName");
			}
		}
		string _UserName;


        [System.Xml.Serialization.XmlElement("Pwd")]
        [Column] 
		public string Pwd 
		{ 
			get
			{
				return _Pwd;
			}
			set
			{
				_Pwd = value;
				MarkColumnModified("Pwd");
			}
		}
		string _Pwd;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_instockitem")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_instockitem : DbEntityDB.Record<t_instockitem>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("InStockNo")]
        [Column] 
		public string InStockNo 
		{ 
			get
			{
				return _InStockNo;
			}
			set
			{
				_InStockNo = value;
				MarkColumnModified("InStockNo");
			}
		}
		string _InStockNo;


        [System.Xml.Serialization.XmlElement("ItemName")]
        [Column] 
		public string ItemName 
		{ 
			get
			{
				return _ItemName;
			}
			set
			{
				_ItemName = value;
				MarkColumnModified("ItemName");
			}
		}
		string _ItemName;


        [System.Xml.Serialization.XmlElement("ItemNo")]
        [Column] 
		public string ItemNo 
		{ 
			get
			{
				return _ItemNo;
			}
			set
			{
				_ItemNo = value;
				MarkColumnModified("ItemNo");
			}
		}
		string _ItemNo;


        [System.Xml.Serialization.XmlElement("CostPrice")]
        [Column] 
		public decimal CostPrice 
		{ 
			get
			{
				return _CostPrice;
			}
			set
			{
				_CostPrice = value;
				MarkColumnModified("CostPrice");
			}
		}
		decimal _CostPrice;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("Num")]
        [Column] 
		public int Num 
		{ 
			get
			{
				return _Num;
			}
			set
			{
				_Num = value;
				MarkColumnModified("Num");
			}
		}
		int _Num;


        [System.Xml.Serialization.XmlElement("WareName")]
        [Column] 
		public string WareName 
		{ 
			get
			{
				return _WareName;
			}
			set
			{
				_WareName = value;
				MarkColumnModified("WareName");
			}
		}
		string _WareName;


        [System.Xml.Serialization.XmlElement("AreaName")]
        [Column] 
		public string AreaName 
		{ 
			get
			{
				return _AreaName;
			}
			set
			{
				_AreaName = value;
				MarkColumnModified("AreaName");
			}
		}
		string _AreaName;


        [System.Xml.Serialization.XmlElement("LocName")]
        [Column] 
		public string LocName 
		{ 
			get
			{
				return _LocName;
			}
			set
			{
				_LocName = value;
				MarkColumnModified("LocName");
			}
		}
		string _LocName;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_item")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_item : DbEntityDB.Record<t_item>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("ItemName")]
        [Column] 
		public string ItemName 
		{ 
			get
			{
				return _ItemName;
			}
			set
			{
				_ItemName = value;
				MarkColumnModified("ItemName");
			}
		}
		string _ItemName;


        [System.Xml.Serialization.XmlElement("ItemNo")]
        [Column] 
		public string ItemNo 
		{ 
			get
			{
				return _ItemNo;
			}
			set
			{
				_ItemNo = value;
				MarkColumnModified("ItemNo");
			}
		}
		string _ItemNo;


        [System.Xml.Serialization.XmlElement("CostPrice")]
        [Column] 
		public decimal CostPrice 
		{ 
			get
			{
				return _CostPrice;
			}
			set
			{
				_CostPrice = value;
				MarkColumnModified("CostPrice");
			}
		}
		decimal _CostPrice;


        [System.Xml.Serialization.XmlElement("Price")]
        [Column] 
		public decimal Price 
		{ 
			get
			{
				return _Price;
			}
			set
			{
				_Price = value;
				MarkColumnModified("Price");
			}
		}
		decimal _Price;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_adjinvtitem")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_adjinvtitem : DbEntityDB.Record<t_adjinvtitem>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("AdjInvtNo")]
        [Column] 
		public string AdjInvtNo 
		{ 
			get
			{
				return _AdjInvtNo;
			}
			set
			{
				_AdjInvtNo = value;
				MarkColumnModified("AdjInvtNo");
			}
		}
		string _AdjInvtNo;


        [System.Xml.Serialization.XmlElement("ItemName")]
        [Column] 
		public string ItemName 
		{ 
			get
			{
				return _ItemName;
			}
			set
			{
				_ItemName = value;
				MarkColumnModified("ItemName");
			}
		}
		string _ItemName;


        [System.Xml.Serialization.XmlElement("ItemNo")]
        [Column] 
		public string ItemNo 
		{ 
			get
			{
				return _ItemNo;
			}
			set
			{
				_ItemNo = value;
				MarkColumnModified("ItemNo");
			}
		}
		string _ItemNo;


        [System.Xml.Serialization.XmlElement("CostPrice")]
        [Column] 
		public decimal CostPrice 
		{ 
			get
			{
				return _CostPrice;
			}
			set
			{
				_CostPrice = value;
				MarkColumnModified("CostPrice");
			}
		}
		decimal _CostPrice;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("OldQty")]
        [Column] 
		public int OldQty 
		{ 
			get
			{
				return _OldQty;
			}
			set
			{
				_OldQty = value;
				MarkColumnModified("OldQty");
			}
		}
		int _OldQty;


        [System.Xml.Serialization.XmlElement("NowQty")]
        [Column] 
		public int NowQty 
		{ 
			get
			{
				return _NowQty;
			}
			set
			{
				_NowQty = value;
				MarkColumnModified("NowQty");
			}
		}
		int _NowQty;


        [System.Xml.Serialization.XmlElement("WareName")]
        [Column] 
		public string WareName 
		{ 
			get
			{
				return _WareName;
			}
			set
			{
				_WareName = value;
				MarkColumnModified("WareName");
			}
		}
		string _WareName;


        [System.Xml.Serialization.XmlElement("AreaName")]
        [Column] 
		public string AreaName 
		{ 
			get
			{
				return _AreaName;
			}
			set
			{
				_AreaName = value;
				MarkColumnModified("AreaName");
			}
		}
		string _AreaName;


        [System.Xml.Serialization.XmlElement("LocName")]
        [Column] 
		public string LocName 
		{ 
			get
			{
				return _LocName;
			}
			set
			{
				_LocName = value;
				MarkColumnModified("LocName");
			}
		}
		string _LocName;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_ware")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_ware : DbEntityDB.Record<t_ware>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("WareName")]
        [Column] 
		public string WareName 
		{ 
			get
			{
				return _WareName;
			}
			set
			{
				_WareName = value;
				MarkColumnModified("WareName");
			}
		}
		string _WareName;


        [System.Xml.Serialization.XmlElement("WareCode")]
        [Column] 
		public string WareCode 
		{ 
			get
			{
				return _WareCode;
			}
			set
			{
				_WareCode = value;
				MarkColumnModified("WareCode");
			}
		}
		string _WareCode;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_area")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_area : DbEntityDB.Record<t_area>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("AreaName")]
        [Column] 
		public string AreaName 
		{ 
			get
			{
				return _AreaName;
			}
			set
			{
				_AreaName = value;
				MarkColumnModified("AreaName");
			}
		}
		string _AreaName;


        [System.Xml.Serialization.XmlElement("AreaCode")]
        [Column] 
		public string AreaCode 
		{ 
			get
			{
				return _AreaCode;
			}
			set
			{
				_AreaCode = value;
				MarkColumnModified("AreaCode");
			}
		}
		string _AreaCode;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
    
	[TableName("t_location")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
	[Serializable]
    public partial class t_location : DbEntityDB.Record<t_location>  
    {

        [System.Xml.Serialization.XmlElement("Id")]
        [Column] 
		public int Id 
		{ 
			get
			{
				return _Id;
			}
			set
			{
				_Id = value;
				MarkColumnModified("Id");
			}
		}
		int _Id;


        [System.Xml.Serialization.XmlElement("Guid")]
        [Column] 
		public Guid Guid 
		{ 
			get
			{
				return _Guid;
			}
			set
			{
				_Guid = value;
				MarkColumnModified("Guid");
			}
		}
		Guid _Guid;


        [System.Xml.Serialization.XmlElement("LocName")]
        [Column] 
		public string LocName 
		{ 
			get
			{
				return _LocName;
			}
			set
			{
				_LocName = value;
				MarkColumnModified("LocName");
			}
		}
		string _LocName;


        [System.Xml.Serialization.XmlElement("LocCode")]
        [Column] 
		public string LocCode 
		{ 
			get
			{
				return _LocCode;
			}
			set
			{
				_LocCode = value;
				MarkColumnModified("LocCode");
			}
		}
		string _LocCode;


        [System.Xml.Serialization.XmlElement("AreaName")]
        [Column] 
		public string AreaName 
		{ 
			get
			{
				return _AreaName;
			}
			set
			{
				_AreaName = value;
				MarkColumnModified("AreaName");
			}
		}
		string _AreaName;


        [System.Xml.Serialization.XmlElement("AreaCode")]
        [Column] 
		public string AreaCode 
		{ 
			get
			{
				return _AreaCode;
			}
			set
			{
				_AreaCode = value;
				MarkColumnModified("AreaCode");
			}
		}
		string _AreaCode;


        [System.Xml.Serialization.XmlElement("WareName")]
        [Column] 
		public string WareName 
		{ 
			get
			{
				return _WareName;
			}
			set
			{
				_WareName = value;
				MarkColumnModified("WareName");
			}
		}
		string _WareName;


        [System.Xml.Serialization.XmlElement("WareCode")]
        [Column] 
		public string WareCode 
		{ 
			get
			{
				return _WareCode;
			}
			set
			{
				_WareCode = value;
				MarkColumnModified("WareCode");
			}
		}
		string _WareCode;


        [System.Xml.Serialization.XmlElement("Remark")]
        [Column] 
		public string Remark 
		{ 
			get
			{
				return _Remark;
			}
			set
			{
				_Remark = value;
				MarkColumnModified("Remark");
			}
		}
		string _Remark;


        [System.Xml.Serialization.XmlElement("CreateDate")]
        [Column] 
		public DateTime CreateDate 
		{ 
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate = value;
				MarkColumnModified("CreateDate");
			}
		}
		DateTime _CreateDate;


        [System.Xml.Serialization.XmlElement("Creator")]
        [Column] 
		public string Creator 
		{ 
			get
			{
				return _Creator;
			}
			set
			{
				_Creator = value;
				MarkColumnModified("Creator");
			}
		}
		string _Creator;


        [System.Xml.Serialization.XmlElement("IsUsing")]
        [Column] 
		public bool IsUsing 
		{ 
			get
			{
				return _IsUsing;
			}
			set
			{
				_IsUsing = value;
				MarkColumnModified("IsUsing");
			}
		}
		bool _IsUsing;


        [System.Xml.Serialization.XmlElement("TimeStamp")]
        [Column] 
		public byte[] TimeStamp 
		{ 
			get
			{
				return _TimeStamp;
			}
			set
			{
				_TimeStamp = value;
				MarkColumnModified("TimeStamp");
			}
		}
		byte[] _TimeStamp;

	}
}


